{{- if .Values.orchestrator.groups.primary.psk.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orchestrator.primaryGroupPSKSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orchestrator.labels" . | nindent 4 }}
type: Opaque
data:
  psk: {{ .Values.orchestrator.groups.primary.psk.value | b64enc }}
{{- end }}