{{- with .Values.orchestrator.groups.primary.psk -}}
{{- if .createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orchestrator.primaryGroupPSKSecretName" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "orchestrator.labels" $ | nindent 4 }}
type: Opaque
data:
  {{ required "A valid key name for the PSK is required!" .secretKey }}: {{ required "A valid 32-byte PSK is required!" .value | b64enc }}
{{- end }}
{{- end }}
