apiVersion: v2
name: orchestrator
description: |
  Maverics Identity Orchestrator (also referred to as an "Orchestrator") is a
  distributed identity management platform that abstracts authentication and session
  management, connects to any identity/attribute system, replicates and synchronizes
  policies and configurations.
home: https://www.strata.io/
icon: https://raw.githubusercontent.com/strata-io/helm-charts/main/assets/logo_maverics.png

annotations:
  # RedHat Marketplace metadata.
  charts.openshift.io/archs: x86_64
  charts.openshift.io/name: Strata - Maverics Identity Orchestrator
  charts.openshift.io/provider: Strata Identity, Inc.
  charts.openshift.io/supportURL: https://github.com/strata-io/helm-charts

type: application

# This is the chart version. This version number should be incremented each time we
# make changes to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.4

# This is the version number of the application being deployed. This version number
# should be incremented each time we make changes to the application. Versions are
# not expected to follow Semantic Versioning. They should reflect the version the
# application is using. It is recommended to use it with quotes.
appVersion: "0.23.31"

# Our minimum Kubernetes version is 1.24.0. This is the version of Kubernetes that
# we have tested and verified that the chart works with. Users are free to try
# earlier versions, but we do not support them. We also do not guarantee that the
# chart will work with newer versions of Kubernetes that we have not tested with
# yet. We will update this field as we test and verify compatibility with newer
# versions. It is recommended to use it with quotes (e.g. '>=1.24.0'). This is
# required by RedHat Marketplace for certification of the chart.
#
# Before changing this value, please check compatibility with customer deployments.
kubeVersion: '>=1.24.0'

keywords:
  - identity
  - orchestration
  - authentication
  - authorization
  - idp
  - oidc
  - saml
  - webauthn
  - cybersecurity
  - mesh

maintainers:
  - name: gramidt
    email: granville@strata.io
